telegram:
  bot:
    username: ${BOT_NAME}
    token: ${BOT_TOKEN}
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT

db:
  driver:
    name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/db
  user: root
  password: root

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true
  format_sql: true
  hbm2ddl:
    auto: update

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
#    username: root
#    password: root
    hikari:
      maximum-pool-size: 10